version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: BELLABEAUTY_DB
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: ADMIN
      POSTGRES_ROOT_PASSWORD: root_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
